name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: vpk-11/workflows/.github/workflows/pages-deploy.yml@v1
    with:
      path: './dist'
      pm: 'pnpm'
